# Generated by Django 3.0.6 on 2020-08-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0009_attendee_contact_m2m'),
        ('persons', '0013_family_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='contacts',
            field=models.ManyToManyField(through='persons.FamilyContact', to='whereabouts.Contact'),
        ),
    ]
