# Generated by Django 3.0.2 on 2020-01-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0002_assembly_contact'),
        ('whereabouts', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assemblies',
            field=models.ManyToManyField(through='occasions.AssemblyContact', to='occasions.Assembly'),
        ),
    ]
