# order matters
from .attending import AttendingSerializer
from .attendee_minimal_serializer import AttendeeMinimalSerializer
from .attending_minimal_serializer import AttendingMinimalSerializer
from .attendingmeet_etc_serializer import AttendingMeetEtcSerializer
from .attendee import AttendeeSerializer
